.github/workflows/ci.yaml
Cargo.lock
Cargo.toml

CHORE: Update fvm deps.

---

Cargo.lock
Cargo.toml
Makefile
fendermint/app/Cargo.toml
fendermint/app/src/main.rs
fendermint/vm/actor_interface/src/eam.rs
fendermint/vm/actor_interface/src/lib.rs
fendermint/vm/interpreter/Cargo.toml
fendermint/vm/interpreter/src/fvm/bundle.rs
fendermint/vm/interpreter/src/fvm/mod.rs
fendermint/vm/interpreter/src/fvm/state/genesis.rs

Part of #41  
Forgot to create the EAM actor in #47 
Also added a test to check that loading from the CAR bundle works.

FM-41: Create EAM actor

---

Cargo.lock
fendermint/app/Cargo.toml
fendermint/app/src/cmd/rpc.rs
fendermint/vm/message/Cargo.toml
fendermint/vm/message/src/signed.rs

Moves message signing to a reusable place.

RF: Move signing to messages crate

---

Cargo.lock
Cargo.toml
docs/running.md
fendermint/app/src/app.rs
fendermint/app/src/cmd/rpc.rs
fendermint/app/src/main.rs
fendermint/app/src/options/parse.rs
fendermint/app/src/options/rpc.rs
fendermint/app/src/tmconv.rs
fendermint/rpc/Cargo.toml
fendermint/rpc/examples/simplecoin.rs
fendermint/rpc/src/client.rs
fendermint/rpc/src/lib.rs
fendermint/rpc/src/message.rs
fendermint/rpc/src/query.rs
fendermint/rpc/src/tx.rs
fendermint/vm/actor_interface/src/eam.rs

Closes #80 
Adds a `simplecoin.rs` example under `fendermint/rpc` to demonstrate using the RPC client to call FEVM through the Tendermint API and interact with a contract in a statically typed fashion.
<details>
<summary><h2>Sample run</h2></summary>
```console
❯ cargo run -p fendermint_rpc --release --example simplecoin -- --secret-key test-network/keys/alice.sk --verbose
Compiling fendermint_rpc v0.1.0 (/home/aakoshh/projects/consensuslab/fendermint/fendermint/rpc)
Finished release [optimized] target(s) in 22.49s
Running `target/release/examples/simplecoin --secret-key test-network/keys/alice.sk --verbose`
2023-04-06T11:13:01.000503Z DEBUG fendermint_rpc::client: Using HTTP client to submit request to: http://127.0.0.1:26657/
2023-04-06T11:13:01.000697Z DEBUG …
```

FM-80: Deploy and call FEVM from a script

---

fendermint/eth/api/src/apis/eth.rs
fendermint/eth/api/src/conv/from_tm.rs
fendermint/eth/api/src/filters.rs
fendermint/eth/api/src/state.rs

FM-211: eth address in logs and filters

---

Cargo.lock
Cargo.toml
fendermint/app/config/default.toml
fendermint/app/src/cmd/eth.rs
fendermint/app/src/settings.rs
fendermint/eth/api/Cargo.toml
fendermint/eth/api/examples/ethers.rs
fendermint/eth/api/src/apis/eth.rs
fendermint/eth/api/src/cache.rs
fendermint/eth/api/src/conv/from_tm.rs
fendermint/eth/api/src/filters.rs
fendermint/eth/api/src/lib.rs
fendermint/eth/api/src/state.rs
fendermint/vm/actor_interface/src/eam.rs

Closes #213 
Depends on #212
Added an `AddressCache` to cache `ActorID <-> DelegatedAddress` relations.

FM-213: Cache actor ID and address

---

fendermint/app/src/tmconv.rs
fendermint/vm/interpreter/src/fvm/check.rs

FM-227: Return error message from nonce and balance checks

---

fendermint/vm/interpreter/src/fvm/query.rs

We found a bug for which when several subsequent messages are being sent, sometimes the gas estimation returned by the gas estimation is exactly the `gas_used` producing transactions to fail. I am not proud of this, but an easy way to fix it is to add an additional overestimation after the `gas_search`. This is not critical, the only impact that it has is that less transactions will fit a block (as the block limit will be reached earlier), and users will have to put more funds upfront for the execution. However, once the message is executed, the FVM will return the funds for the outstanding gas that wasn't used in the execution of the message.
This should be a temporary fix until we come up with a better strategy to estimate gas more accurately in a way it that doesn't return `gas_search …

fix: additional overestimation to estimateGas

---

.gitignore
docker/local.Dockerfile

This PR fixes the docker file to run e2e-tests.

Fix docker e2e

---

Cargo.lock
Cargo.toml
fendermint/vm/resolver/src/pool.rs

Update async stm to 0.4

---

Cargo.lock
fendermint/app/config/default.toml
fendermint/app/settings/src/eth.rs
fendermint/app/settings/src/lib.rs
fendermint/app/settings/src/resolver.rs
fendermint/app/src/cmd/rpc.rs
fendermint/app/src/cmd/run.rs
fendermint/rpc/src/lib.rs
fendermint/rpc/src/tx.rs
fendermint/vm/encoding/src/lib.rs
fendermint/vm/genesis/src/lib.rs
fendermint/vm/interpreter/Cargo.toml
fendermint/vm/interpreter/src/fvm/broadcast.rs
fendermint/vm/interpreter/src/fvm/checkpoint.rs
fendermint/vm/interpreter/src/fvm/exec.rs
fendermint/vm/interpreter/src/fvm/mod.rs
fendermint/vm/interpreter/src/fvm/state/exec.rs
fendermint/vm/interpreter/src/fvm/state/fevm.rs
fendermint/vm/interpreter/src/fvm/state/ipc.rs
fendermint/vm/ipc_actors/src/gateway_diamond.rs
fendermint/vm/ipc_actors/src/gateway_getter_facet.rs
fendermint/vm/ipc_actors/src/gateway_manager_facet.rs
fendermint/vm/ipc_actors/src/gateway_messenger_facet.rs
fendermint/vm/ipc_actors/src/gateway_router_facet.rs
fendermint/vm/ipc_actors/src/subnet_actor_diamond.rs
fendermint/vm/ipc_actors/src/subnet_actor_getter_facet.rs
fendermint/vm/ipc_actors/src/subnet_actor_manager_facet.rs
fendermint/vm/ipc_actors/src/subnet_registry.rs
fendermint/vm/message/src/signed.rs

Closes #255 
Depends on: 
* https://github.com/consensus-shipyard/fendermint/pull/278 
* https://github.com/consensus-shipyard/fendermint/pull/273
* https://github.com/consensus-shipyard/fendermint/pull/280
The PR adds a step after creating a checkpoint and adding it to the ledger to create and broadcast a transaction that adds the validator signature.

FM-255: Sign checkpoint

---

infra/run.sh

This PR fixes a minor bug in infra's `run.sh`.

Check network name variable

---

fendermint/vm/interpreter/src/fvm/exec.rs
fendermint/vm/interpreter/src/fvm/mod.rs

Related to #255 
As the title says, when a node re-syncs from genesis or catching up and encounters checkpoints which were already finished without its assistance, there's no need to send the signature again.

FM-255: Skip broadcasting checkpoint signature if syncing

---

fendermint/app/config/default.toml
fendermint/app/settings/src/fvm.rs
fendermint/app/settings/src/lib.rs
fendermint/app/settings/src/resolver.rs
fendermint/app/src/cmd/run.rs
fendermint/rpc/src/query.rs
fendermint/vm/interpreter/src/fvm/broadcast.rs

Closes #282 
Retries broadcasting the transaction up to 5 times if it fails with nonce problems.

FM-282: Retry broadcast

---

fendermint/app/src/app.rs

Closes #165 
Changes the `AppHash` we return in commits from just the state root hash (which includes the actor state) to be the CID of the `FvmStateParams` record which we keep the history of. This one contains the root hash, plus anything else that might change as a result of contract execution, such as the circulating supply.
I kept it as a CID just in case in the future we want to make it available from the `Blockstore`, even though at the moment it's not retrievable as such.

FM-165: Use the CID of FvmStateParams for AppHash

---

docs/running.md
fendermint/app/options/src/key.rs
fendermint/app/src/cmd/key.rs

Convert Eth private key to fendermint keys.

Convert eth private key to fendermint

---

docs/running.md
fendermint/app/options/src/key.rs
fendermint/app/src/cmd/key.rs
fendermint/app/src/cmd/run.rs

Fix eth address conversion here and there in the code base.

Fix eth address conversion

---

fendermint/eth/api/src/filters.rs

Fixes #221  
Use the `matches_topics` function in subscriptions to only return logs which the subscription asked for.

FM-221: Filter logs by topics in subscriptions

---

fendermint/vm/genesis/src/lib.rs

The PR changes `Collateral::into_power` to round up, away from zero, to avoid degenerate cases of little collateral resulting in 0 power, e.g. if we have 1 validator and choose lower collateral than the power scale, (either in genesis, or because the parent subnet doesn't enforce it in join), then we end up with 0 total power and are unable to create a checkpoint.

FIX: Round up during collateral to power conversion

---

infra/Makefile.toml
infra/scripts/cometbft.toml
infra/scripts/node.toml
infra/scripts/testnet.toml

This PR changes the sed separator to not collide with the subnet ID.

fix sed separator

---

Cargo.lock
fendermint/app/src/cmd/run.rs
fendermint/vm/topdown/Cargo.toml
fendermint/vm/topdown/src/sync.rs

Stops parent finality syncing with parent if the current node is syncing with peers.

Check if syncing with peer

---

fendermint/eth/api/src/handlers/ws.rs

Fixes #418 
Changes the web socket handler to return a flag indicating whether the connection should be closed. I thought we'd receive some event that would hit the `else` in the tokio loop when the connection is closed, but apparently not.
Unsubscription confirmed in the logs:
```console
2023-11-09T23:56:33.867918Z  WARN fendermint_eth_api::handlers::ws: failed to send notfication to WS web_socket_id=0 error=Error { inner: AlreadyClosed }
2023-11-09T23:56:33.867955Z DEBUG fendermint_eth_api::handlers::ws: Removing WS connection web_socket_id=0
...
2023-11-09T23:56:34.409843Z DEBUG fendermint_eth_api::filters: web socket no longer listening id=11367411595152612149
...
2023-11-09T23:56:34.992303Z DEBUG fendermint_eth_api::filters: filter no longer listening, quiting subscription …
```

FM-418: Close web socket when unable to send

---

fendermint/vm/snapshot/src/manager.rs

Closes #359 
Removes snapshot directories if we have more than a configured number exported.

FM-359: Remove old snapshots

---

Cargo.lock
Cargo.toml
fendermint/eth/hardhat/src/lib.rs
fendermint/testing/contract-test/src/ipc/registry.rs
fendermint/testing/contract-test/src/ipc/subnet.rs
fendermint/testing/contract-test/tests/staking/machine.rs
fendermint/vm/actor_interface/src/ipc.rs
fendermint/vm/interpreter/src/fvm/genesis.rs
fendermint/vm/topdown/src/proxy.rs

Use the new `SubnetRegistryDiamond` and its facets. 
Depends on https://github.com/consensus-shipyard/ipc/pull/406 and https://github.com/consensus-shipyard/ipc-solidity-actors/pull/298

FIX: Use SubnetRegistryDiamond

---

fendermint/app/config/default.toml
fendermint/app/settings/src/lib.rs
fendermint/app/src/cmd/run.rs
fendermint/vm/snapshot/src/manager.rs

Closes #356 
Adds settings for snapshots. For now they are disabled, until the tests are completed.

FM-356: Snapshot config

---

Cargo.lock
fendermint/testing/contract-test/tests/staking/machine.rs

Upgrade dependencies to propagate the changes from https://github.com/consensus-shipyard/ipc-solidity-actors/pull/305

IPC-304: upgrade contracts
