consensus-shipyard/fendermint

.github/workflows/ci.yaml, Cargo.lock, fendermint/app/Cargo.toml
Closes #6 
Added a dependency on `forest_db` in the Forest github project itself, at the latest tagged version. For some reason only an old version of `forest_db` is published on `crates.io`, so we have to use the `git` dependency. I'm using the `tag` rather than the `version`, so we have a clear commit - not sure how up to date the version 0.2.0 is.
In fact, they changed it to flat versioning across the whole repo [just an hour ago](https://github.com/ChainSafe/forest/pull/2487/files#diff-d6b8d669c7ef9b11b5eac3711804bd142460eade316de5e0de894defc8ea6dfb).
=> FM-6: Add dependency on forest_db

Cargo.lock, Cargo.toml, Makefile, fendermint/app/Cargo.toml, fendermint/app/src/main.rs
Closes #8 
Added `ref-fvm` stuff and the `next` branch of `builtin-actors` (a.k.a. actors V10) as dependencies and tried if they can be loaded into RocksDB.
=> FM-8: FVM and built-in actor dependencies

.github/workflows/ci.yaml, Makefile
Looking at the `sccache` setup and post logs [before](https://github.com/consensus-shipyard/fendermint/actions/runs/4057626181 and [after](https://github.com/consensus-shipyard/fendermint/actions/runs/4057880432) merging a PR, the cache behaviour is confusing. Before the merge, the logs say the cache is found for `Lint (stable)` and `Test (stable)`, but both have 100% cache misses. `Test (nightly)` works as expected. After the merge, on `master`, no caches are found, even though the restore key is the same. 
I will try to separate the Lint and Test caches, maybe that will at least make them behave like nightly and avoid the cache hits.
Ah, Github isolates caches per branch: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-access …
=> CI: Separate caches.

Cargo.lock, Cargo.toml, fendermint/vm/message/Cargo.toml, fendermint/vm/message/src/chain_message.rs, fendermint/vm/message/src/lib.rs, fendermint/vm/message/src/signed_message.rs
Closes #11 
The PR brings over parts of the [message](https://github.com/ChainSafe/forest/tree/main/vm/message) crate from Forest. Only the `SignedMessage` was copied more or less as-is; the `ChainMessage` also got an equivalent, but its contents are different.
The location mirrors the `vm` directory in Forest, which I thought might provide some familiar structure, with the eventual `interpreter` dealing with the FVM. But, those Forest modules are not something which I can reuse: they are built against FVM v2 (as opposed to v3 which we are targeting here) and already reflect some parts of Expected Consensus.
NB the `Cbor` trait has been removed from the `builtin-actors` and `ref-fvm`.
=> FM-11: Message model

Cargo.lock, Cargo.toml, fendermint/app/src/app.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/cron.rs, fendermint/vm/actor_interface/src/lib.rs, fendermint/vm/actor_interface/src/system.rs, fendermint/vm/interpreter/Cargo.toml, fendermint/vm/interpreter/src/fvm.rs
Closes #15 
Created a `fendermint/vm/actor_interface` crate (similar to Forest) with copies of actor IDs and methods (similar to the FVM) as a consolidation point for how to invoke built-in actors.
Calling the `cron` actor in `begin_block`. 
TODO: Which actors the `cron` actor is calling seems to depend entirely on constructor arguments, that is, it's defined in genesis. We identified that we'll only keep actors which probably don't have regular jobs to do at the beginning of the blocks. Things like applying power transitions need to happen at the end of the blocks - maybe we should move the cron to the end, from the beginning? Probably not, nobody used to FVM in Lotus/Forest would expect that. Should we have another general actor to call? Or just call it from the interpreter - that seems …
=> FM-15: Cron actor interface

Cargo.lock, Cargo.toml, Makefile, fendermint/app/Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/main.rs, fendermint/vm/interpreter/src/fvm.rs
Related to #17 
I thought the version of FVM released last week already contained the PR which made the fields of `StampedEvent` public, but not yet, so I can't finish this PR right now.
When I tried to update the version of `fvm` and `fvm_shared` to the latest version, it turned out that the `builtin-actors` insist on an earlier version of `fvm_shared`. This is unfortunate, now we are dependent on the release cycle of both `fvm*` and `builtin-actors` before we can use a new FVM feature. 
This PR changes the way `builtin-actors` are used in the single test where their bundle is loaded, so that instead of compiling them as a project reference, the repo is cloned in a `make` task, compiled, and the CAR file exported. Hopefully they will work, as long as nothing in the interfaces became …
=> FM-17: Produce actor bundle CAR separately 

Cargo.lock, Cargo.toml, fendermint/testing/Cargo.toml, fendermint/testing/src/lib.rs, fendermint/testing/src/smt.rs
Create a `fendermint/testing` crate with utilities we might want to reuse in our tests. 
The only example for now is the state machine tester I added for the EVM. It wasn't used there, but I plan to make use of it here.
=> FM-16: Bring over SMT

Cargo.lock, Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/main.rs, fendermint/storage/Cargo.toml, fendermint/storage/src/im.rs, fendermint/storage/src/lib.rs, fendermint/storage/src/tests.rs
Related to #16 
This PR brings over some code I developed a while ago when I wanted to use RocksDB with transactions, and column families. It creates a `KVStore` abstraction that we can implement, with `KVReadable` and `KVWriteable` traits to show whether something requires read-only or read-write access. Further to that, it defines `Encode`, `Decode` and `Codec` traits to do the actual serialization. 
Currently in Forest they use a `DB: Blockstore + Store` generic parameter to access IPLD data under the default namespace and also to store arbitrary key-value pairs as bytes, for example [here](https://github.com/ChainSafe/forest/blob/v0.6.0/blockchain/chain/src/store/chain_store.rs#L704). 
```rust
pub fn set_genesis<DB>(db: &DB, header: &BlockHeader) -> Result<Cid, Error>
where
DB: …
```
=> FM-16: Storage abstraction

Cargo.lock, Cargo.toml, fendermint/app/Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/lib.rs, fendermint/app/src/main.rs, fendermint/app/src/store.rs, fendermint/rocksdb/Cargo.toml, fendermint/rocksdb/src/blockstore.rs, fendermint/rocksdb/src/kvstore.rs, fendermint/rocksdb/src/lib.rs, fendermint/rocksdb/src/rocks/config.rs, fendermint/rocksdb/src/rocks/error.rs, fendermint/rocksdb/src/rocks/mod.rs, fendermint/storage/src/lib.rs
Related to #16 
Implements `KVStore` for RocksDB. Unfortunately I could not use the Forest RocksDB library any more, because even if I specified the `multi-threaded-cf` feature which is required for `.transaction()`, I had to create an `OptimisticTransactionDB`, not a `DB`, so I ended up copying a lot of the Forest code. 
The PR changes `App` to use `KVStore`. 
In this instance, after so much work, it doesn't make a difference because we don't modify the app state concurrently, nor do we perform multiple steps during writes/reads. Still, it felt right to put the data into a different column family, and at least this way we can use the same abstraction elsewhere in the application, like for relayers. Another area is where it can help is supporting queries by maintaining a list of the past …
=> FM-16: RocksDB

fendermint/app/src/app.rs, fendermint/rocksdb/src/kvstore.rs, fendermint/storage/src/im.rs, fendermint/storage/src/lib.rs, fendermint/storage/src/tests.rs
Closes #25
The PR removes the `prepare()` method because it works differently in RocksDB than I imagined. Unlike `put`, `delete` and `commit`, the docs do not mention that it could return `Busy`, so I imagine that it does not check for conflicts. It might do, but it doesn't say, just that it prepares for two phase commit by writing changes to the WAL. 
I got rid of it in favor of allowing `commit` to return `KVResult::Conflict` to signal that it failed. I will update STM to expect this workflow.
=> FM-25: Remove KVPreparedTransaction

Cargo.lock, Cargo.toml, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/message/Cargo.toml, fendermint/vm/message/src/arb_cid.rs, fendermint/vm/message/src/chain.rs, fendermint/vm/message/src/lib.rs, fendermint/vm/message/src/signed.rs
Related to #30 
The PR contains `Arbitrary` instances for messages and a quickcheck test to make sure a `ChainMessage` can be serialized to/from binary as intended with IPLD.
I had to fix some of the arbitrary data generated by the upstream libraries: 
* `TokenAmount` has a `BigInt` that can be too large to serialize according to the Filecoin spec.
* `DelegatedAddress` has a `length` field that had a value inconsistent with how many bytes it had filled with non-zero values. 
I don't know if these were done like this deliberately as "completely arbitrary" or they are a result of oversight.
I added two `ChainMessage` types that I do not intend to handle in Milestone 1, but I wanted to see if they work with the serialization.
There is a version conflict with the `cid` and `multihash` …
=> FM-30: Binary format tests

Cargo.lock, Cargo.toml, fendermint/app/Cargo.toml, fendermint/app/src/app.rs
Closes #17 
Now that a new version of `fvm_shared` made the necessary fields public, was able to finish mapping events. 
I think the Go version of `EventAttribute` might accept `bytes`, which it turns into Base64 strings during serialization; the Rust library expects `String` for key and value, which it will encode as Base64. The value coming from `StampedEvent` is `Vec<u8>`, so I first converted it `hex`, which then will be converted into Base64, which is a bit ugly, but not sure what else I could do (apart from double Base64 encoding, which could be shorter, but perhaps we use hex more often).
Here are some relevant docs:
* https://docs.cosmos.network/v0.46/core/events.html
* https://docs.tendermint.com/v0.34/tendermint-core/subscription.html
* …
=> FM-17: Map events to ABCI

fendermint/app/src/app.rs, fendermint/app/src/main.rs
Closes #36 
The PR adds a `KVCollection<S, BlockHeight, Cid>` to the `App` where it stores a fixed (currently 1 days worth, thinking 1 second blocks, which is the Tendermint default) number of historical entries for state root hashes. 
These are pruned and inserted during block `commit`, and used during `query` to figure out what state we can run our query on. If the height the user is looking for is no longer maintained, we return the latest height.
=> FM-36: Save state root history

fendermint/app/Cargo.toml, fendermint/app/src/cmd/mod.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/lib.rs, fendermint/app/src/main.rs, fendermint/app/src/options.rs
As a preparation for #54, the PR moves the implementation of the `Commands` into a new `cmd` module. For now I am keeping all commands in the `fendermint_app` crate. 
```console
$ target/debug/fendermint --help
Usage: fendermint [OPTIONS] [COMMAND]
Commands:
run
Run the [`App`], listening to ABCI requests from Tendermint
help
Print this message or the help of the given subcommand(s)
Options:
-c, --config-dir <FILE>
Set a custom directory for configuration files.
By default the application will try to find where the config directory is.
-d, --debug...
Turn debugging information on
-h, --help
Print help (see a summary with '-h')
-V, --version
Print version
```
=> RF: Move commands to submodule

Cargo.lock, fendermint/app/Cargo.toml, fendermint/app/src/cmd/keygen.rs, fendermint/app/src/cmd/mod.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/main.rs, fendermint/app/src/options.rs, fendermint/vm/genesis/src/lib.rs
Closes #54 
Adds a `keygen` command to generate a public and private key pair. 
```console
❯ target/debug/fendermint keygen --help
Generate a new Secp256k1 key pair and export them to files in base64 format
Usage: fendermint keygen [OPTIONS] --name <NAME>
Options:
-n, --name <NAME>        Name used to distinguish the files from other exported keys
-o, --out-dir <OUT_DIR>  Directory to export the key files to; it must exist [default: .]
-h, --help               Print help
```
```console
❯ mkdir test-keys
❯ target/debug/fendermint keygen --name alice --out-dir test-keys
❯ ls test-keys
alice.pk  alice.sk
❯ cat test-keys/alice.pk
A9+3i7HR5ijRI2naXwCf1yCO40NO1BB8KTuAtGkzIwZ2⏎         
```
=> FM-54: Keygen

Cargo.lock, Cargo.toml, fendermint/app/Cargo.toml, fendermint/app/config/default.toml, fendermint/app/src/cmd/mod.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/options.rs, fendermint/app/src/settings.rs, fendermint/app/src/store.rs, fendermint/rocksdb/src/lib.rs, fendermint/rocksdb/src/namespaces.rs, fendermint/rocksdb/src/rocks/mod.rs
Contains two fixes:
* Opening RocksDB a second time needs all the column families to be passed up front
* Expanding the `~` in the paths in the config
```console
❯ cargo run -p fendermint_app -- --config-dir ./fendermint/app/config -ddd  run
...
Running `target/debug/fendermint --config-dir ./fendermint/app/config -ddd run`
2023-03-27T16:04:10.752139Z  INFO fendermint::cmd::run: opening database path="/home/aakoshh/.fendermint/data/rocksdb"
2023-03-27T16:04:11.085806Z  INFO tower_abci::server: starting ABCI server addr="127.0.0.1:26658"
2023-03-27T16:04:11.085922Z  INFO tower_abci::server: bound tcp listener local_addr=127.0.0.1:26658
```
=> FIX: Open db and paths

Cargo.lock, fendermint/app/Cargo.toml, fendermint/app/src/cmd/genesis.rs, fendermint/app/src/cmd/mod.rs, fendermint/app/src/options.rs, fendermint/vm/genesis/src/arb.rs, fendermint/vm/genesis/src/encoding.rs, fendermint/vm/genesis/src/lib.rs
Closes #57 
Adds a CLI command to create a new genesis file.
```console
❯ cargo run -p fendermint_app -- genesis new --help
...
Running `target/debug/fendermint genesis new --help`
Create a new Genesis file, with accounts and validators to be added later
Usage: fendermint genesis --genesis-file <GENESIS_FILE> new [OPTIONS] --network-name <NETWORK_NAME> --base-fee <BASE_FEE>
Options:
--network-name <NETWORK_NAME>
Name of the network and chain
--network-version <NETWORK_VERSION>
Network version, governs which set of built-in actors to use [default: 18]
--base-fee <BASE_FEE>
Base fee for running transactions
-h, --help
Print help
```
```console
❯ cargo run -p fendermint_app -- genesis --genesis-file ./genesis.json new --network-name test --base-fee 1000
❯ cat genesis.json
{
"network_name": …
```
=> FM-57: Genesis / New command

docs/running.md, fendermint/app/config/default.toml, fendermint/app/src/cmd/mod.rs, fendermint/app/src/main.rs, fendermint/app/src/options.rs, fendermint/app/src/settings.rs
Related to #58 
Makes the CLI options more intuitive and more like those of Tendermint:
* Added a `--log-level` option instead of counting the number of `-d`; added an `off` option as well, defaults to `info`.
* Added a `--home-dir` to set a directory which can be used as the root of all paths in the config file, unless they are absolute paths, or are based on `~` which is the user home directory; defaults to `~/.fendermint`. 
* Removed the `--config-dir` option. This way there is no confusion over where the config is, and then what paths are pointing at inside the config files.
```console
❯ cargo run -p fendermint_app -- help
Compiling fendermint_app v0.1.0 (/home/aakoshh/projects/consensuslab/fendermint/fendermint/app)
Finished dev [unoptimized + debuginfo] target(s) in 29.89s
Running …
```
=> FM-58: Change CLI opts

docs/running.md, fendermint/app/src/cmd/genesis.rs, fendermint/app/src/cmd/key.rs, fendermint/app/src/cmd/mod.rs, fendermint/app/src/options.rs
Closes #67
Adds CLI command to convert `.sk` files to the format Tendermint expects for private validator key files. 
```console
$ cargo run -p fendermint_app -- key into-tendermint --help
Convert a secret key file from base64 into the format expected by Tendermint
Usage: fendermint key into-tendermint --secret-key <SECRET_KEY> --out <OUT>
Options:
-s, --secret-key <SECRET_KEY>  Path to the secret key we want to convert to Tendermint format
-o, --out <OUT>                Output file name for the Tendermint private validator key JSON file
-h, --help                     Print help
```
I had to construct the JSON manually because the `tendermint-config` Rust library doesn't handle Secp256k1 keys, but hopefully it's all the same to Tendermint - otherwise why does it let us specify it in the …
=> FM-67: CLI convert secret key to Tendermint format

docs/running.md, fendermint/app/src/cmd/key.rs
Fixes #67 
Tendermint did not expect unpadded base64 keys. The PR changes the engine to be lenient when reading, strict when writing.
=> FM-67: Use padded base64 encoding

docs/running.md, fendermint/app/config/default.toml, fendermint/app/src/app.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/settings.rs, fendermint/rocksdb/src/rocks/mod.rs, fendermint/vm/interpreter/src/fvm/check.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/mod.rs, fendermint/vm/interpreter/src/fvm/state/check.rs, fendermint/vm/interpreter/src/fvm/state/exec.rs, fendermint/vm/interpreter/src/fvm/state/genesis.rs, fendermint/vm/interpreter/src/fvm/state/mod.rs
Part of #58 
Fixed some problems with the application:
* When opening the DB the first time we must not pass any column families, we must create them after open. On subsequent opens we must pass all existing column families. The PR changes `RocksDB::open` to use the `list_cf` method to figure out what exists and pass it back, then we call `new_cf_handle` for anything that does not `has_cf_handle`.
* Initialize the application state during `App::new` so the initial `info` request does not fail. 
* Cache the wasm engine otherwise it will take a very long time to execute blocks, not just the first one.
=> FM-58: Start the App and TM

fendermint/app/src/app.rs, fendermint/app/src/main.rs, fendermint/rocksdb/src/blockstore.rs
Fixes #71 
During testing it turned out that I when I restart the Application and reconnect to it from Tendermint, the Application crashes because it cannot find the manifest root CID in the block store. It's weird because on the first start some additional debug logs clearly show that it is written and subsequently successfully retrieved as well. I also added a test to verify that I can reopen a database that has the actor bundle imported and the manifest can be restored. 
My only hunch was that maybe somehow the disabling of the WAL during bulk writes can result in this particular key being lost upon a restart. I don't understand why; I don't see anything special in Forest that would deal with this, although IIRC it might be single threaded where I switched to multi-threaded. Maybe the …
=> FM-58: Use WAL 

Cargo.lock, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/options/parse.rs, fendermint/app/src/options/rpc.rs
Closes #83 
Adds a `transact` command to send raw byte parameters to an actor method. More for completeness' sake, as I don't have a good way to construct these parameters without running a program. 
```console
❯ cargo run -p fendermint_app -- rpc transact --help
Finished dev [unoptimized + debuginfo] target(s) in 0.39s
Running `target/debug/fendermint rpc transact --help`
Send a message (a.k.a. transaction) to an actor
Usage: fendermint rpc transact [OPTIONS] --secret-key <SECRET_KEY> --to <TO> --sequence <SEQUENCE> --method-number <METHOD_NUMBER> --params <PARAMS>
Options:
-s, --secret-key <SECRET_KEY>
Path to the secret key of the sender to sign the transaction
-t, --to <TO>
Address of the actor to send the message to
-v, --value <VALUE>
Amount of tokens to send, in atto
[default: 0] …
```
=> FM-83: CLI transact command

Cargo.lock, Cargo.toml, docs/running.md, fendermint/app/Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/options/rpc.rs, fendermint/app/src/tmconv.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/cron.rs, fendermint/vm/actor_interface/src/eam.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/state/exec.rs
Closes #79 
Adds a `fevm create` command to deploy an EVM contract from source. It prints out the different addresses assigned by the EAM actor to help call the contract.
```console
./target/release/fendermint rpc fevm --help
Subcommands related to FEVM
Usage: fendermint rpc fevm [OPTIONS] --secret-key <SECRET_KEY> --sequence <SEQUENCE> <COMMAND>
Commands:
create
Deploy an EVM contract from source; print the results as JSON
help
Print this message or the help of the given subcommand(s)
Options:
-v, --value <VALUE>
Amount of tokens to send, in atto
[default: 0]
-s, --secret-key <SECRET_KEY>
Path to the secret key of the sender to sign the transaction
-n, --sequence <SEQUENCE>
Sender account nonce
--gas-limit <GAS_LIMIT>
Maximum amount of gas that can be charged
[default: 10000000000] …
```
=> FM-79: CLI command to deploy FEVM contract

Cargo.lock, docs/running.md, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/options/rpc.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/evm.rs, fendermint/vm/actor_interface/src/lib.rs
Closes #86 
Adds a `fevm invoke` method to pass raw ABI values to contracts.
```console
❯ cargo run -p fendermint_app --release -- rpc fevm invoke --help
Finished release [optimized] target(s) in 0.84s
Running `target/release/fendermint rpc fevm invoke --help`
Call an EVM contract; print the results as JSON with the return data rendered in hexadecimal format
Usage: fendermint rpc fevm --secret-key <SECRET_KEY> --sequence <SEQUENCE> invoke [OPTIONS] --contract <CONTRACT> --method <METHOD>
Options:
-c, --contract <CONTRACT>        Either the actor ID based or the EAM delegated address of the contract to call
-m, --method <METHOD>            ABI encoded method hash, expected to be in hexadecimal format
-m, --method-args <METHOD_ARGS>  ABI encoded call arguments passed to the EVM, expected to …
```
=> FM-86: Invoke contract CLI

Cargo.lock, Cargo.toml, docs/running.md, fendermint/app/Cargo.toml, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/options/rpc.rs, fendermint/rpc/Cargo.toml, fendermint/rpc/src/client.rs, fendermint/rpc/src/lib.rs, fendermint/rpc/src/message.rs, fendermint/rpc/src/query.rs, fendermint/rpc/src/response.rs, fendermint/rpc/src/tx.rs
Closes #77 
Created a `fendermint_rpc` crate and moved over a lot of the functionality from `fendermint_app::cmd::rpc`. 
It contains the following:
* `QueryClient` trait to perform `ipld` and `actor_state` queries, parsing into the right return values
* `TxClient` trait to perform `transfer`, `transaction`, `fevm_create` and `fevm_invoke` commands parsing into the expected return types depending on what `BroadcastMode` is chosen
* `FendermintClient` which doesn't have keys, so it can only do queries
* `BoundFendermintClient` which is bound to keys and maintains sequences via `MessageFactory`
* `MessageFactory` to just construct payload without making any calls
Allowing `TxClient` to support multiple modes made it a bit complicated because the command line makes the broadcast mode a …
=> FM-77: RPC client

docs/running.md, fendermint/app/src/cmd/rpc.rs
Human readable output seems more useful at this point for demoing the solution. 
It maybe better UX for anyone trying to use the CLI to automation some workflow to have to install `jq` rather than for anyone not having `jq` to get unreadable JSON one liners.
=> CLI/RPC: Change the JSON output to be pretty printed.

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, Dockerfile, Makefile, docs/running.md, fendermint/app/src/options/mod.rs, fendermint/testing/smoke-test/.gitignore, fendermint/testing/smoke-test/Cargo.toml, fendermint/testing/smoke-test/Makefile.toml, fendermint/testing/smoke-test/scripts/init.sh, fendermint/testing/smoke-test/src/lib.rs, rust-toolchain.toml
Closes #95 
Adds a `fendermint/testing/smoke-test` crate with [cargo-make](https://github.com/sagiegurari/cargo-make) that sets up Fendermint and Tendermint as docker containers and runs the simplecoin example.
=> FM-95: Automated smoke test

fendermint/app/src/app.rs, fendermint/vm/genesis/src/lib.rs, fendermint/vm/interpreter/src/fvm/genesis.rs, fendermint/vm/interpreter/src/fvm/state/exec.rs
Part of #93 
The PR changes the application to save the full `FvmStateParams` record rather than just the state hash, at each block height. The record also gets a `timestamp` field that contains the genesis timestamp in the beginning, and the block timestamp later.
=> FM-93: Save full state params

fendermint/app/src/app.rs, fendermint/app/src/tmconv.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/fvm/state/query.rs, fendermint/vm/interpreter/src/fvm/store/mod.rs, fendermint/vm/message/src/query.rs
Closes #93 
Introduces an `FvmQuery::Call(Message)` variant that executes a query in read-only mode. It doesn't require signature, so we can execute from the point of view of any account.
=> FM-93: Call query

Makefile, docker/ci.Dockerfile, docker/local.Dockerfile, docs/running.md
The end-to-end test takes 45 minutes, of which 20 minutes is building docker, and 15 minutes is building the simplecoin example. The PR tries to speed it up by building the app on the CI server, not inside the docker image, so that it can take advantage of sccache. Locally it will use the other pattern, although the builtin actors are still built on the machine.
=> CHORE: Make docker build faster on CI

Cargo.lock, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/options/rpc.rs, fendermint/rpc/Cargo.toml, fendermint/rpc/examples/simplecoin.rs, fendermint/rpc/src/client.rs, fendermint/rpc/src/message.rs, fendermint/rpc/src/query.rs, fendermint/rpc/src/response.rs, fendermint/rpc/src/tx.rs, fendermint/testing/smoke-test/Makefile.toml
Closes #94 
Adds a `fevm call` CLI command which has the same parameters as `fevm invoke`, plus an additional `height`, and sends a message to be run without invoking a transaction. It uses the new `fevm_call` method added to a new `CallClient` trait in the RPC library.
```console
❯ cargo run -p fendermint_app --release -- rpc fevm call --help
Finished release [optimized] target(s) in 0.46s
Running `target/release/fendermint rpc fevm call --help`
Call an EVM contract without a transaction; print the results as JSON with the return data rendered in hexadecimal format
Usage: fendermint rpc fevm --secret-key <SECRET_KEY> --sequence <SEQUENCE> call [OPTIONS] --contract <CONTRACT> --method <METHOD>
Options:
-c, --contract <CONTRACT>        Either the actor ID based or the EAM delegated address …
```
=> FM-94: FEVM call

Cargo.lock, Cargo.toml, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/evm.rs
Closes #106
We can upgrade to 3.2, but to go to 3.3 or 3.4 is thwarted by `frc42_dispatch` depending on 3.2
We can try to remove that dependency by hardcoding the hash, like the FVM integration tests do :persevere: 
We only have 1 method to hash, so this isn't too bad at the moment, but if in the future there would be more, I would switch back to using the hasher.
Perhaps it was a one-off, but the test times were faster without this dependency (the 3.2 and 3.4 tests were running concurrently, so it's not down to caching).
=> FM-106: Upgrade FVM version to 3.4

Cargo.lock, Cargo.toml, docs/demos/milestone-1/README.md, docs/running.md, docs/tendermint.md, fendermint/abci/examples/kvstore.rs, fendermint/app/Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/cmd/key.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/tmconv.rs, fendermint/rpc/Cargo.toml, fendermint/rpc/src/client.rs, fendermint/rpc/src/query.rs, fendermint/testing/smoke-test/Makefile.toml, fendermint/testing/smoke-test/scripts/init.sh, fendermint/vm/message/src/chain.rs
Closes #107 
As a side effect of catching up with `tendermint-rs`, I had to change what the `FvmQuery::Call` ABCI query gets back in response. This is the one that is running a transaction in a local read-only fashion. Previously I returned an IPLD encoded `DeliverTx` construct from `tendermint-rs` itself, so that the client library has the same fields and data types to work with when it comes to seeing transaction results. However, the `Deserialize` trait was removed from this type, so while I could turn it into bytes with `fvm_ipld_encoding`, there wasn't a way to get it back. Apparently they introduced a `dialect` module which will have complete `serde` support, it's generic in its even payloads, which is where I guess there were some differences across consumers. 
To get around this …
=> FM-107: Switch to cometbft

fendermint/app/src/app.rs, fendermint/app/src/cmd/run.rs, fendermint/rocksdb/src/blockstore.rs, fendermint/rocksdb/src/lib.rs, fendermint/rocksdb/src/rocks/mod.rs
Closes #112 
Added a `NamespaceBlockstore` to separate the data that is only supposed to be writeable for actors. In the future the IPLD Resolver should use its own namespace to write data, but it can also use this one to read data.
=> FM-112: Use a namespace for state store

Cargo.lock, Cargo.toml, fendermint/abci/src/application.rs, fendermint/app/Cargo.toml, fendermint/app/config/default.toml, fendermint/app/src/cmd/eth.rs, fendermint/app/src/cmd/mod.rs, fendermint/app/src/options/eth.rs, fendermint/app/src/options/mod.rs, fendermint/app/src/settings.rs, fendermint/eth/api/Cargo.toml, fendermint/eth/api/src/lib.rs
Part of #99 
Establishes a `fendermint_eth_api` library crate which can listen to the JSON-RPC and eventually WebSocket requests from Ethereum tools. This is started as another command under `fendermint_app`:
```console
❯ cargo run -p fendermint_app --release -q -- eth run --help
Run the Ethereum JSON-RPC facade
Usage: fendermint eth run [OPTIONS]
Options:
-u, --url <URL>              The URL of the Tendermint node's RPC endpoint [env: TENDERMINT_RPC_URL=] [default: http://127.0.0.1:26657]
--proxy-url <PROXY_URL>  An optional HTTP/S proxy through which to submit requests to the Tendermint node's RPC endpoint
-h, --help                   Print help
```
Further to these options, we have some extra settings in `default.toml`:
```toml
[eth]
[eth.http]
host = "127.0.0.1"
port = 8545
[eth.ws] …
```
=> FM-99: Ethereum API facade entry

Cargo.lock, docs/running.md, fendermint/rpc/Cargo.toml, fendermint/rpc/examples/simplecoin.rs, fendermint/testing/smoke-test/Makefile.toml
Follow up for #111 
Do away with the `--chain-name` parameter in the SimpleCoin example by querying the Tendermint `genesis()` API endpoint and using the `chain_id` field. It makes it easier to call the example (similar to how it figures out the nonce) and demonstrates the use of the underlying Tendermint client.
=> FM-111: Query the chain ID from genesis in SimpleCoin example

Cargo.lock, Cargo.toml, docker/ci.Dockerfile, docker/local.Dockerfile, fendermint/app/src/cmd/eth.rs, fendermint/eth/api/Cargo.toml, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/lib.rs, fendermint/eth/api/src/rpc_http_handler.rs, fendermint/rpc/Cargo.toml, fendermint/rpc/examples/simplecoin.rs, fendermint/testing/smoke-test/Makefile.toml
Part of #99 
Start registering `eth` method handlers, and call the ones already implemented _and_ available through `ethers-providers` as part of the smoke tests.
=> FM-99: Register methods and call in smoke test

Cargo.lock, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/options/rpc.rs, fendermint/app/src/tmconv.rs, fendermint/rpc/Cargo.toml, fendermint/rpc/examples/simplecoin.rs, fendermint/rpc/src/query.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/fvm/state/query.rs, fendermint/vm/message/src/query.rs
Closes #120
Adds a new ABCI query, RPC and CLI method to retrieve the state parameters comprising of `circ_supply`, `base_fee`, `network_version` and `chain_id`.
```console
$ cargo run -q -p fendermint_app --release -- rpc query --help
Send an ABCI query
Usage: fendermint rpc query [OPTIONS] <COMMAND>
Commands:
ipld          Get raw IPLD content; print it as base64 string
actor-state   Get the state of an actor; print it as JSON
state-params  Get the slowly changing state parameters
help          Print this message or the help of the given subcommand(s)
Options:
-b, --height <HEIGHT>  Block height to query; 0 means latest [default: 0]
-h, --help             Print help
❯ cargo run -q -p fendermint_app --release -- rpc query state-params --help
Get the slowly changing state parameters …
```
=> FM-120: ABCI query for state params

Cargo.lock, Cargo.toml, fendermint/vm/core/Cargo.toml, fendermint/vm/core/src/chainid.rs
Closes #122 
Switches to using FNV hash for chain ID like the IPC agent library. Also parses the `"/r123"` format for rootnet chain IDs.
=> FM-122: Use FNV hasher for chain ID

Cargo.lock, fendermint/app/src/cmd/genesis.rs, fendermint/app/src/options/genesis.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/vm/actor_interface/src/eam.rs, fendermint/vm/actor_interface/src/ethaccount.rs, fendermint/vm/actor_interface/src/lib.rs, fendermint/vm/actor_interface/src/placeholder.rs, fendermint/vm/genesis/Cargo.toml, fendermint/vm/genesis/src/arb.rs, fendermint/vm/interpreter/src/fvm/genesis.rs, fendermint/vm/interpreter/src/fvm/state/genesis.rs
Closes #125 
* Added a `--kind` parameter to the `fendermint genesis add-account` CLI command which can be `regular` (default) or `ethereum`. Depending on its value the public key is hashed as an `f1` or an `f410` address.
* The genesis interpreter inspects the `owner` of the account and if it's an `f410` address it creates the state with the `ethaccount` code ID and sets the `delegated_address`.
=> FM-125: Ethereum accounts in genesis

Cargo.lock, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/conv/from_eth.rs, fendermint/eth/api/src/state.rs, fendermint/rpc/src/response.rs, fendermint/testing/smoke-test/scripts/init.sh, fendermint/vm/actor_interface/src/burntfunds.rs, fendermint/vm/actor_interface/src/lib.rs, fendermint/vm/actor_interface/src/reward.rs, fendermint/vm/interpreter/src/fvm/genesis.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/signed.rs, fendermint/vm/message/Cargo.toml, fendermint/vm/message/src/conv/from_eth.rs, fendermint/vm/message/src/conv/from_fvm.rs, fendermint/vm/message/src/conv/mod.rs, fendermint/vm/message/src/query.rs, fendermint/vm/message/src/signed.rs
Part of #99 
Implements the following Ethereum API methods:
* `eth_call`
* `eth_estimateGas`
Using those, it tests transaction deployment of `SimpleCoin` and calling `get_balance` (a pure function exercising `eth_call`).
=> FM-99: Ethereum API methods (Part 4)

Cargo.lock, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/state.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/eam.rs, fendermint/vm/actor_interface/src/evm.rs, fendermint/vm/interpreter/src/fvm/state/query.rs
Part of #99 
Added new methods:
* eth_getBlockReceipts
* eth_getStorageAt
* eth_code
* eth_syncing
What's left are methods of the event API (which require web sockets) and non-eth methods.
=> FM-99: Ethereum API methods (Part 5)

fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/apis/net.rs, fendermint/eth/api/src/apis/web3.rs
Part of #99 
Closes #133 and #134 
* eth_protocolVersion
* web3_clientVersion
* web3_sha3
* net_version
* net_listening
* net_peerCount
All that's left is the event API (filters and subscriptions).
=> FM-99: Ethereum API methods (Part 6)

Cargo.lock, Cargo.toml, docker/ci.Dockerfile, docker/local.Dockerfile, fendermint/app/Cargo.toml, fendermint/app/config/default.toml, fendermint/app/src/cmd/eth.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/options/eth.rs, fendermint/app/src/settings.rs, fendermint/app/src/tmconv.rs, fendermint/eth/api/Cargo.toml, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs, fendermint/eth/api/src/lib.rs, fendermint/eth/api/src/state.rs, fendermint/rpc/src/client.rs, fendermint/testing/smoke-test/Makefile.toml
Closes #137 
Adds API methods related to filters:
* eth_newFilter
* eth_newBlockFilter
* eth_pendingTransactionFilter
* eth_uninstallFilter
* eth_getFilterChanges
Caveats:
* Instead of pending transactions, we return transactions which are included in blocks, as that's what we are able to subscribe to
* Logs returned in subscriptions don't have `block_hash`, `transaction_index` and `log_start_index` fields as these would require further queries to the API, with caching to avoid hammering the node.
TODO: 
* Check how Etherscan deals with the extra fields in logs.
* Follow up with a test to parse the logs with the ethers machinery.
=> FM-137: Ethereum API filter methods

fendermint/eth/api/Cargo.toml, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/filters.rs, fendermint/eth/api/src/state.rs
Closes #140 
Adds to #137 
Changes:
* Added eth_getFilterLogs
* Randomized filter ID to be unpredictable
* Changed the subscription/filter to use channels for communication, rather than locking mutexes
=> FM-140: Replace Mutex with Channel

Cargo.lock, Cargo.toml, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/error.rs, fendermint/eth/api/src/filters.rs, fendermint/eth/api/src/handlers/http.rs, fendermint/eth/api/src/handlers/mod.rs, fendermint/eth/api/src/handlers/ws.rs, fendermint/eth/api/src/lib.rs, fendermint/eth/api/src/state.rs, fendermint/rpc/src/client.rs
Closes #138 
Part of #99
Implements two new methods:
* eth_subscribe
* eth_unsubscribe
The filter system now can work either in polling or push based fashion.
The ethers example has been modified to exercise the JSON-RPC requests over both HTTP and WS protocols. 
TODO:
=> FM-138: Ethereum API methods: eth_subscribe

fendermint/eth/api/src/apis/eth.rs
Depends on #163 
In order to finalize the tooling integration (and for Remix to be able to make calls to a contract), we had to also accept legacy transaction transactions for call queries.
=> FM-170: add transaction compat to call query

fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/fvm/state/query.rs
This addresses issue #176.
This PR removes the state_tree option and just use exec_state, which also exposes a state_tree_mut() method now, to avoid any discrepancy, and then you can chain call and actor_state calls freely.
=> Use exec state

.github/workflows/ci.yaml
The PR changes the CI workflow to skip running the test matrix if the PR is in the _Draft_ state. 
I usually like to open draft PRs as soon as possible for visibility, but frequently find myself cancelling PR runs just to save the resources - they run long, and sometimes I know the tests won't pass. 
We still run pre-compile checks to catch simple things like formatting errors which are quick and easy  to check.
=> CHORE: Skip tests on draft PRs

.github/actions/install-tools/action.yaml, .github/workflows/ci.yaml
@aakoshh Apologies but I missed this while reviewing #188. When specifying the `toolchain`, we should use the `master` branch of the action rather than `stable` (per https://github.com/dtolnay/rust-toolchain#inputs). I don't think it breaks anything right now but better avoid unsupported combinations.
=> FM-186: Fix rust-toolchain action version

fendermint/abci/src/application.rs, fendermint/abci/src/lib.rs, fendermint/abci/src/util.rs, fendermint/app/src/app.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/interpreter/src/bytes.rs, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/interpreter/src/lib.rs
Closes #184 
The PR introduces a `ProposalInterpreter` similar to the ones which already exist, so that we can keep the `app.rs` free of much of our application logic, and farm it out into the layers where the different types and representations of messages are handled. 
Currently it does nothing new, accepts everything. The goal was to introduce this necessary boilerplate and agree on the abstractions.
My motivation was to help https://github.com/consensus-shipyard/fendermint/pull/181 focus on the top-down message without having to decode messages in the application root.
=> FM-184: Proposal interpreter

Cargo.lock, Cargo.toml, fendermint/abci/Cargo.toml, fendermint/app/Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/cmd/run.rs, fendermint/app/src/lib.rs, fendermint/vm/interpreter/Cargo.toml, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/message/src/ipc.rs, fendermint/vm/resolver/Cargo.toml, fendermint/vm/resolver/src/lib.rs, fendermint/vm/resolver/src/pool.rs
Closes #191 
Depends on #198
_The PR looks bigger than it is because it merged `main`, and because after running `cargo update` there are lots of changes to `Cargo.lock` and `ethers` also generated different code for Solidity actors. We can rebase once the dependencies are merged._
=> FM-191: Execute BottomUpResolve

fendermint/app/src/app.rs, fendermint/vm/interpreter/src/chain.rs
Closes #196 
Depends on #201 and #185
Implements `ProposalInterpreter::process` method for `ChainMessageInterpreter` by looking up proposed checkpoints for execution in the `ResolvePool` and checking that the item is present and resolved, otherwise we don't vote for the proposal.
=> FM-196: Implement ProposalInterpreter::process for BottomUp

Cargo.lock, Cargo.toml, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/resolver/src/pool.rs
Closes #195 
Depends on #202 
Added a `ResolvePool::collect_resolved` method to gather all resolved items, which are appended to the messages as checkpoints proposed for execution by the `ChainMessageInterpreter` in the `ProposalInterpreter::prepare` method implementation.
=> FM-195: Implement ProposalInterpreter::prepare for BottomUp

.github/workflows/ci.yaml, Cargo.toml, Makefile, fendermint/eth/api/src/apis/eth.rs, fendermint/vm/interpreter/src/bytes.rs, fendermint/vm/interpreter/src/fvm/genesis.rs, scripts/add_license.sh
My [build](https://github.com/consensus-shipyard/fendermint/actions/runs/5964638421/job/16180310789?pr=214) started complaining about new clippy violations, ran on Rust 1.72, because we run `make lint` on `nightly` on CI. 
It turns out some of those seem to be false alarms due to a bugs in clippy, reporting that an `&mut` should be just `&`, while that's not the case. 
The PR changes CI to run Clippy on `stable`, while fixes some of the things raised while still in nightly mode. We don't run the full `make lint` any more because `make check-fmt` requires nightly, and is already part of the `Pre-compile checks` step.
=> CHORE: Fix lint

fendermint/app/src/app.rs, fendermint/app/src/tmconv.rs, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/conv/from_eth.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs, fendermint/eth/api/src/state.rs, fendermint/rpc/examples/simplecoin.rs, fendermint/vm/core/src/chainid.rs, fendermint/vm/interpreter/src/bytes.rs, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/fvm/state/check.rs, fendermint/vm/interpreter/src/fvm/state/exec.rs, fendermint/vm/interpreter/src/fvm/state/query.rs, fendermint/vm/interpreter/src/signed.rs, fendermint/vm/message/src/signed.rs
Fixes #216 
I renamed some of the output types from the interpreters:
* if the output is some kind of an enum or record type that contains positive as well as negative results, it has a `Ret` suffix (like the `ApplyRet` type of the FVM)
* if the output is an alias for a `Result` with a custom error, and a positive going in the `Ok` side, it has a `Res` suffix
This way I could replace the `SingedMessageApplyRet` type which was a `Result<FvmApplyRet, SignatureError>` with two new types: `SignedMessageApplyRes` is now the alias for this `Result` and `SignedMessageApplyRet` is the positive case which includes the FVM result as well as the sighash of the message. 
This renaming was carried out on the other output types as well. I know `Ret` and `Res` are so close to each other it may be …
=> FM-216: Index transactions by Ethereum hash

fendermint/app/src/app.rs, fendermint/app/src/tmconv.rs, fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs, fendermint/eth/api/src/state.rs, fendermint/vm/interpreter/src/bytes.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/interpreter/src/signed.rs, fendermint/vm/message/src/signed.rs
Fixes #216 
Depends on #217 
I missed the fact that Lotus returned the Keccak256 hash of the full raw transaction including the signature RLP, not the sighash. Which makes sense because in Ethereum the `from` is not reified in the transaction payload, only inferred from the signature, so without the signature two transactions doing the same thing sent from different account (with the same nonce) would not be unique unless the signature was also hashed.
This PR drop the `sig.hash` field introduced in #217 and adds an `eth.hash` field instead based on a new `SignedMessage::domain_hash(&self, chain_id)` method that returns an optional `DomainHash`, with currently only the `DomainHash::Eth` variant defined. In the API we always look for the value in events, to keep it simple - if it's not …
=> FM-216: Index transaction by Ethereum hash (take 2)

fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/conv/from_tm.rs
This PR: 
- Fixes an error for which `logs_bloom` was being set to `null` when serializing the response for `eth_getBlockBy...` which made some tooling to crash in the deserialization of the response because it expects a mandatory `logs_bloom` field.
- Improves logging for debugging purposes.
=> fix: getBlock null bloom

Cargo.lock, fendermint/app/config/default.toml, fendermint/app/config/test.toml, fendermint/app/options/src/rpc.rs, fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/rpc.rs, fendermint/app/src/cmd/run.rs, fendermint/rpc/examples/simplecoin.rs, fendermint/rpc/src/message.rs, fendermint/vm/interpreter/src/fvm/broadcast.rs
Closes #283 
Changes the `validator_key` setting from a `PathBuf` into a struct with a `path` and a `kind` field, where the kind can be `regular` or `ethereum`, which is how accounts are added to the genesis file too. This is then used to derive the `addr` which is passed to the `Broadcaster` and the `MessageFactory`, which allows validators to use f410 accounts to pay for transactions. 
I thought about introducing two of these fields, one for the validator (needs to sign the checkpoint, but there the account kind isn't needed) and an optional one for the broadcaster (can be used to override the validator key for sending transactions) but decided to hold on, since we discussed in a comment with @adlrocha that recognising validator transactions could be something we use to subsidize their …
=> FM-283: Add validator account kind setting

fendermint/vm/interpreter/src/fvm/checkpoint.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/state/ipc.rs
Closes #259 
The PR changes the end-of-period checkpoint signature broadcasting by validators to apply on all incomplete (a.k.a. pending) checkpoints where they were validators.
So, instead of doing this on node start, it's done on each checkpoint period end. This has the following benefits:
* `main.rs` stays simpler and the checkpointing logic is kept in the interpreter
* a validator doesn't have to restart their node to fill in their signatures if e.g. they ran out of funds, they just need to get some tokens and it will automatically be retried
=> FM-259: Sign all incomplete checkpoints

.gitignore, Makefile, scripts/find-ipc-actors.sh
This is a followup for https://github.com/consensus-shipyard/fendermint/pull/297
Before that PR, `make ipc-actors-abi` checked out the `ipc-solidity-actors` repository and compiled the ABI artifacts, which were then used to:
1. generate Rust bindings and 
2. copy the contracts into the Docker file. 
Which tag to check out was defined in the `Makefile` as `IPC_ACTORS_TAG` which could be overridden as an env var.
After that PR, we no longer had to do 1), but still needed the checkout for 2). However now the `IPC_ACTORS_TAG` could have differed from the tag defined in `Cargo.toml` where the project dependency was defined.
This PR removes the need for checking out the `ipc-solidity-actors` repo by finding where `cargo` did the checkout and generating the ABI bindings there.
=> CHORE: Generate the ABI under the IPC actor solidity checkout

Cargo.lock, Cargo.toml, docs/running.md, fendermint/app/Cargo.toml, fendermint/app/options/Cargo.toml, fendermint/app/options/src/genesis.rs, fendermint/app/options/src/parse.rs, fendermint/app/src/cmd/genesis.rs, fendermint/testing/smoke-test/scripts/init.sh, fendermint/vm/genesis/src/arb.rs, fendermint/vm/genesis/src/lib.rs, infra/scripts/node.toml, infra/scripts/testnet.toml
Closes #306 
This PR implements a new genesis command to generate the genesis file for a child subnet from the information available for the child in the parent (after it has been bootstrapped successfully).
=> FM-306: Create child subnet genesis from parent

fendermint/app/src/app.rs, fendermint/vm/interpreter/src/chain.rs, fendermint/vm/interpreter/src/fvm/state/exec.rs, fendermint/vm/interpreter/src/fvm/state/genesis.rs, fendermint/vm/interpreter/src/fvm/state/ipc.rs, fendermint/vm/interpreter/src/fvm/state/mod.rs, fendermint/vm/interpreter/src/fvm/topdown.rs
Closes #316 
The PR changes the top-down message execution so that it increases the circulating supply with the tokens minted and given to the gateway.
=> FM-316: Top down mint increase circ supply

fendermint/testing/contract-test/tests/smt_staking.rs, fendermint/testing/contract-test/tests/staking/machine.rs, fendermint/vm/actor_interface/src/ipc.rs, fendermint/vm/interpreter/src/fvm/checkpoint.rs, fendermint/vm/interpreter/src/fvm/state/ipc.rs, fendermint/vm/interpreter/src/fvm/topdown.rs
Closes #287 
Changes the checkpoint creation process to include the decrease of circulating supply by the values that are included in the bottom-up messages. 
Introduced some functions to help keep things consistent:
* An `AbiHash` trait is implemented for anything we want to hash in Solidity and match that hash in Rust, to take out the guesswork from tuple or no-tuple. Seemingly unrelated but since I had to retrieve all the cross messages, whereas previously I got the hash directly from the gateway caller, I didn't want to use the naked `abi_hash` function from the interpreter. 
* `tokens_to_mint` and `tokens_to_burn` to sum up the value in cross messages.
* We ignored the `fee` during minting, so I assumed it meant that the fees will be collected in the target network. => _Changed both …
=> FM-287: Bottom up burn decrease circ supply

docker/local.Dockerfile
Fixes `local.Dockerimage` to use Debian `bookworm` and install `libssl3` in both the builder and the runner to avoid this error when _running_ the `fendermint` image (e.g. using `make e2e`):
```
fendermint: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
The reason for the change is because the latest (1.73) rust builder image switched to bookworm.
https://stackoverflow.com/questions/76508361/getting-error-while-loading-shared-libraries-libssl-so-1-1-when-running-docke
=> FIX: Use bookworm with libssl3

docker/local.Dockerfile
It was enough for the builder image to have `libssl3`. 
Follow up to https://github.com/consensus-shipyard/fendermint/pull/336
=> FIX: Remove unnecessary lib

docker/local.Dockerfile, fendermint/app/src/cmd/run.rs, fendermint/testing/smoke-test/Makefile.toml, infra/Makefile.toml, infra/scripts/fendermint.toml
@adlrocha has some trouble configuring his fendermint container to connect to the cometbft one. 
This PR adds an example of configuring the URL in the smoke tests. They aren't used in the smoke tests, but we should see them printed in the logs.
The URL can be configure either as:
1. `TENDERMINT_RPC_URL`, because the `fendermint rpc` and `fendermint eth` commands take it in this format - I thought it might be something people dealing with CometBFT (Tendermint Core at the time) might have. 
2. `FM_TENDERMINT_RPC_URL`, because it's part of the config files and everything there can be overwritten with `FM_` prefix
=> FIX: Set the Tendermint RPC URL for the fendermint container

fendermint/app/src/app.rs, fendermint/app/src/tmconv.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs, fendermint/vm/interpreter/src/fvm/state/mod.rs
Closes #220  
Initially I wanted to add `block.hash` to the indexes but decided against it, and just removed the incorrect filtering of `tx.hash`. 
Then I realised that we can use an index on `block.hash` in filters, where it didn't use to be available, but Ethereum clients expect it.
=> FM-220: Remove tx.hash from the filter, index block.hash

fendermint/app/src/tmconv.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs
Closes #322 
* Renames the current `message.*` events to `event.*` event, which are the events/logs emitted by contracts
* Adds `message.from` and `message.to` to the index
* Subscribes to all combinations of filters with `message.from` and `message.to` as well, just in case that's what the account is meant to match.
* `eth::get_log` matches emitters as well as `from` and `to` against any addresses in the filter.
I though about `tx.from` and `tx.to` but decided against it, so we leave these Tendermint provided `tx` values alone, and because we call them `message` in the FVM anyway, which `from` and `to` are part of, but `tx.hash` and `tx.height` aren't. 
I just noticed that all keys can accept a list of values, so instead of `eth.hash` we could have stuck to `tx.hash` and have two values …
=> FM-322: Index message.to and message.from

fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/filters.rs
Closes #219 
Adds a time based LRU cache to the filter driver and skips duplicate transactions that follow each other within one minute. They should come pretty rapidly, so even that is more than enough time.
=> FM-219: Filter duplicate transactions in subscriptions

fendermint/testing/contract-test/src/ipc/registry.rs, fendermint/vm/actor_interface/src/eam.rs, fendermint/vm/actor_interface/src/init.rs, fendermint/vm/interpreter/src/fvm/state/genesis.rs, fendermint/vm/interpreter/src/fvm/state/ipc.rs
A discussion about how masked IDs should be avoided inside the EVM led to the realisation that adding `EthAddress::into_non_masked` in https://github.com/consensus-shipyard/fendermint/pull/319 as a convenience method was ill-advised because this is not a rule for this type, it's only one made up when I was working on the genesis process for the builtin Ethereum actor IDs, nothing else. They work because the association is manually inserted into the `Init` actor's state, but wouldn't work for any other actor ID which was created through the EAM actor.
=> FIX: Remove EthAddress::into_non_masked

fendermint/app/options/src/eth.rs, fendermint/app/src/cmd/eth.rs, fendermint/rpc/src/client.rs, fendermint/testing/smoke-test/Makefile.toml
The Ethereum API can fail to start if CometBFT is not ready for connection, which is why the smoke tests waited 10-20s after starting `cometbft` before starting the `ethapi` container. 
This PR adds a limited number of retries to the Ethereum API to help with this, by default 5 retries with 5 second delays between them, which should take it above the 20s that worked on CI. 
The `cometbft-wait` task is still present, but it's moved down, so we see the effect of of retries in the log and don't run tests until the API is ready.
=> FIX: Add reconnection to Ethereum API startup

fendermint/eth/api/examples/ethers.rs, fendermint/testing/contract-test/tests/staking/machine.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/eam.rs, fendermint/vm/actor_interface/src/ipc.rs, fendermint/vm/interpreter/src/fvm/checkpoint.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/state/ipc.rs, fendermint/vm/message/src/signed.rs
Fixes #340 
Added a `checkpoint::unsigned_signatures` method that collects incomplete signatures that the current validator hasn't signed, so that they don't try to send their signatures again. 
It turns out that they would not have incurred cost because gas estimation would have failed, as the contract rejects duplicates. But this way they would skip it altogether.
=> FM-340: Don't send duplicate signatures

fendermint/app/config/default.toml, fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/interpreter/src/fvm/broadcast.rs, fendermint/vm/interpreter/src/fvm/checkpoint.rs
Fixes #341 
The PR adds a step to `checkpoint::broadcast_incomplete_signatures` to call `wait_for_commit` with the highest checkpointed height +1, which should make sure that the block where the checkpoint has been added to the ledger has been executed. 
It also adds a `retry_delay` setting to the `Broadcaster` with a default 2s in the configuration file, so in case we run into an issue like this, it gives the thing a chance to at least create a block for the state to change. Previously there was no delay because I thought it's only the nonce that might be having a race condition, but this situation clearly won't resolve itself by an immediate restart.
=> FM-341: Delay broadcasting checkpoint sig after commit

fendermint/vm/interpreter/src/fvm/state/query.rs
Fill the gas limit when it's 0 for `call` type txn. This should fix: #352.
=> Fill gas limit for call

fendermint/vm/message/src/conv/from_eth.rs
Fill the sender with SYSTEM_ACTOR_ADDR if it is None.
Reasons for doing this:
- `eth_call` will work as not every time `from` will be filled.
=> Fill sender if it's None

fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs
Fixes https://github.com/consensus-shipyard/fendermint/issues/350
Consistent with Lotus https://github.com/filecoin-project/lotus/blob/master/node/impl/full/eth.go#L360
=> FM-350: eth_getTransactionCount should return 0 for nonexistent senders

infra/scripts/testnet.toml
After applying duckscript, `testnet` was broken. The problem is that `mkdir` method does not have keys - https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__fs__CreateDirectory
As a result, `-p` directory was created, and `cometbft` directories had root privileges.
=> Fix testnet script

.github/workflows/ci.yaml
We run the unit tests on both `stable` and `nightly` Rust, but I think at the moment because we target `stable` the `nightly` tests don't give enough value to justify the 700MB [cache space](https://github.com/consensus-shipyard/fendermint/actions/caches) they take out of the 10GB allowance on Github Actions. We'd benefit more from leaving it for docker and other stuff.
Workflow was canceled because all I wanted to verify was that it did not want to test nightly.
=> TEST: Disable nightly tests

.github/workflows/ci.yaml
It turns out that https://github.com/consensus-shipyard/fendermint/pkgs/container/fendermint/versions has images going back months now. 
I think we are safe to remove everything that has been orphaned. Hopefully this action does just that: https://github.com/Chizkiyahu/delete-untagged-ghcr-action
I left the PR as _Draft_ because there is no point in testing it, it changes nothing apart from removing stuff if executed on `main`.
=> DOCKER: Delete untagged images after build

docker/builder.ci.Dockerfile
Followup for #374 
The PR does some tricks to try to get more out of the Github Actions caching activated by `--cache-to=type=gha` which works on layers. 
It includes an initial `stripper` stage in the build where all the source code except the `Cargo.toml` and `Cargo.lock` files are stripped away and replaced with empty Rust files. In the `builder` stage these files are copied and built with `cargo`, which results in the download and build of all dependencies into the `target` directory. This gets cached as a Docker layer, and if the dependencies don't change then they can be reused for the next build. After this the rest of the source code is copied in as usual and another round of build produces the final executable. 
* https://stackoverflow.com/questions/49939960/docker-copy-files-usin …
=> DOCKER: Pre-build and cache dependencies

Makefile
Takes the IPC ABI from the cloned repo without compiling it. 
Depends on https://github.com/consensus-shipyard/ipc-solidity-actors/pull/276
=> BUILD: Remove foundry req

.github/actions/setup-cache/action.yaml, .github/workflows/ci.yaml
Our [caches](https://github.com/consensus-shipyard/fendermint/actions/caches) are full of entries with the same hash but different date. I think these have the same content, but they cause other entries to be evicted, especially with repeated builds. A possible reason for why they exist may be that multiple PRs run at the same time and end up with slightly different date timestamps, with both thinking they have to push. 
The PR depends on https://github.com/consensus-shipyard/sccache-action/pull/1 to disable the date suffix and replace it with a unique hash.
=> BUILD: Do not append the date to reduce the number of uploads

fendermint/app/options/src/key.rs, fendermint/app/src/cmd/key.rs
Mirroring https://github.com/consensus-shipyard/fendermint/pull/334 adds a command to convert Base64 keys into hex.
```console
❯ cargo run -q -p fendermint_app --release -- key fendermint-to-eth --help
Converts a Base64 encoded Fendermint private key in a hex encoded Ethereum secret key and address
Usage: fendermint key fendermint-to-eth [OPTIONS] --secret-key <SECRET_KEY> --name <NAME>
Options:
-s, --secret-key <SECRET_KEY>  Path to the file that stores the private key (base64 format)
-n, --name <NAME>              Name used to distinguish the files from other exported keys
-o, --out-dir <OUT_DIR>        Directory to export the key files to; it must exist [default: .]
-h, --help                     Print help
```
=> CMD: Add fendermint-to-eth command

fendermint/app/options/src/key.rs, fendermint/app/src/cmd/key.rs
Follow up for https://github.com/consensus-shipyard/fendermint/pull/393 
```console
❯ cargo run  -p fendermint_app --release -- key --help
Subcommands related to the construction of signing keys
Usage: fendermint key <COMMAND>
Commands:
gen              Generate a new Secp256k1 key pair and export them to files in base64 format
into-tendermint  Convert a secret key file from base64 into the format expected by Tendermint
address          Convert a public key file from base64 into an f1 Address format an print it to STDOUT
add-peer         Get the peer ID corresponding to a node ID and its network address and print it to a local file
from-eth         Converts a hex encoded Ethereum private key into a Base64 encoded Fendermint keypair
into-eth         Converts a Base64 encoded Fendermint …
```
=> FIX: Rename eth-to-fendermint and export .pk and .addr

infra/scripts/fendermint.toml
While testing the end-to-end I realized that no bottom-up checkpoints were being signed in the child subnet. It ended up being because I wasn't passing the `ValidatorContext` settings required for the validator to be able to sign and commit checkpoint signatures. This PR passes the settings to the validator infra scripts as env variables.
=> FIX: pass settings to run bottom-up checkpoints in validator infra

fendermint/eth/api/src/conv/from_tm.rs
Related to https://github.com/consensus-shipyard/fendermint/issues/399#issuecomment-1798758781 in #399 
Sets the `blockHash` and `blockNumber` on the transactions when they are embedded in a block. They are obvious, which is why I thought they don't need to be set in this context, but apparently that is not the case. They are probably optional for the sake of transactions that aren't included in any block.
=> FIX: Set block hash and number in to_eth_block

infra/scripts/fendermint.toml, infra/scripts/subnet.toml
This PR includes two new commands (`child-fullnode` and `child-fullnode-down`) in the infra scripts to deploy full nodes, i.e nodes that don't participate from the consensus, but follow the chain and execute and validate new blocks in the network.
Sample execution to test: 
```
cargo make --makefile ./infra/Makefile.toml \
-e NODE_NAME=validator-2 \
-e SUBNET_ID=/r314159/t410fhvndv5jlebhuzkeeniowduugkadqra3aibnximy \
-e CMT_P2P_HOST_PORT=3305 -e CMT_RPC_HOST_PORT=3306 \
-e BOOTSTRAPS=92f41793a193e37d4b0a27ccce0ef7568b0e42a3@15.204.216.8:26650 \
-e PARENT_REGISTRY=0x2fdf1b18907341b751B32aF7088D32f6f5a617E0 \
-e PARENT_GATEWAY=0x5Be26735Ab7A70B057e76e31953d8811f95b05AC \
child-fullnode
```
=> INFRA: Add IPC full-node infra recipe

fendermint/eth/api/src/conv/from_tm.rs, fendermint/vm/message/src/conv/from_fvm.rs, fendermint/vm/message/src/signed.rs
Sets the `transaction_type` fields on the `ethers::core::type::Transaction` return values in the API to 2, which should signal that `gas_price` will not be set.
=> FIX: Set transaction_type to 2

Cargo.lock, fendermint/app/src/app.rs, fendermint/vm/actor_interface/Cargo.toml, fendermint/vm/actor_interface/src/init.rs, fendermint/vm/interpreter/src/fvm/genesis.rs, fendermint/vm/interpreter/src/fvm/state/genesis.rs
The genesis process actually _was_ deterministic, despite the use of `HashSet` (I think); after adding loads of debug logs it turned out that it was the `genesis.json` we fetch from the parent which ended up having a different order of accounts in them, which resulted in different actor ID to address allocations.
Need to fix the IPC provider for this to go away: https://github.com/consensus-shipyard/ipc/pull/385
=> FIX: Debug genesis non determinism

fendermint/app/src/app.rs, fendermint/testing/smoke-test/Makefile.toml
Trying to replicate `end_block` panicking due to `exec state empty`. 
Steps to replicate:
1. Add a long sleep in `deliver_tx` while the interpreter is owning the state.
2. `make docker-build`
3. `cd fendermint/testing/smoke-tests`
4. `cargo make setup`
5. `cargo make simplecoin-example`
6. `docker logs -f smoke-fendermint`
7. `cargo make teardown`
The logs show that:
```console
2023-11-10T15:00:34.099374Z  INFO fendermint_vm_interpreter::fvm::exec: tx delivered height=17 from="f1kigdcls46syhfzfrmorydy2wdgvunw7alzk2pca" to="f010" method_num=4 exit_code=0
2023-11-10T15:00:34.099445Z  INFO fendermint_app::app: sleeping...
thread 'tokio-runtime-worker' panicked at /app/fendermint/app/src/app.rs:304:22:
exec state empty
stack backtrace:
0: rust_begin_unwind
at …
```
=> FIX: end block no exec state

Cargo.lock, fendermint/app/src/cmd/rpc.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/rpc/Cargo.toml, fendermint/rpc/src/query.rs, fendermint/rpc/src/response.rs, fendermint/rpc/src/tx.rs, fendermint/vm/interpreter/src/fvm/query.rs, fendermint/vm/message/src/query.rs
Closes #408 
The information from the backtrace in the `ApplyFailure` has indeed been returned in the `info` field of the `DeliverTx`, and it also tries to return any potential revert-data as a hexadecimal string. Unfortunately in this case there isn't anything, as demonstrated by the unit test which parses the value seen in the log. 
Nevertheless the Eth API has been changes so that if there was an error parsing the return data, it would append it to the `message` in the error response, so that we don't have to wonder if it swallowed something.
Also changed the gas estimation query to return the `return_data` and parse it looking for potential errors.
=> FM-408: Debug any hidden revert data

docs/running.md, fendermint/app/src/app.rs, fendermint/app/src/cmd/genesis.rs
Added the block height to the `init_chain` logs so we can see what was going on. 
In the `genesis into-tendermint` command I set the `initial_height` of the CometBFT `genesis.json` file to 0, but it doesn't seem to make any difference: I get 1 for initial height in `init_chain`, and the first block it creates also has height 1. The first block also has the timestamp of genesis, so ~it's effectively a physical embodiment of it~, and perhaps the only reason for `init_chain` to exist is so we don't have to come up with transactions that achieve the same effect, but it's considered somehow part of the process. Actually the application hash resulting from `init_chain` is already visible in the header of block 1, so it's a separate step.
```console
023-11-10T12:49:24.035117Z  INFO …
```
=> FIX: Rectify state and block heights

fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/apis/eth.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/eth/api/src/state.rs
Creates a `BLOCK_ZERO` which is returned when the client is looking for one at height 0 or when it's looking for the `BLOCK_ZERO_HASH`. 
Testing through `ethers.rs` example.
=> FIX: Pretend there is a block 0

fendermint/app/config/default.toml, fendermint/app/settings/src/lib.rs, fendermint/app/src/cmd/run.rs, fendermint/vm/interpreter/src/fvm/broadcast.rs, fendermint/vm/interpreter/src/fvm/checkpoint.rs
Changes the mode of broadcasting checkpoint signatures from `TxCommit` to `TxSync`, that is, instead of waiting for `deliver_tx` it only waits for `check_tx`. 
The reason is that looking at the logs, the `broadcast_tx_commit` of the CometBFT API doesn't work the way I thought it did. I thought that it will wait for the commit (`deliver_tx`) of the transaction, but also return early if `check_tx` fails, since the response has the results for both. Instead what we see is that it times out waiting for delivery:
```console
2023-11-13T10:00:20.556795Z  INFO fendermint_vm_interpreter::fvm::query: query actor state height=40862 pending=true addr="t410frbdnwklaitcjsqe7swjwp5naple6vthq4woyfry" found=true
2023-11-13T10:00:20.557981Z  INFO fendermint_vm_interpreter::fvm::query: query estimate gas …
```
=> FIX: Change checkpoint broadcast mode to sync

fendermint/vm/interpreter/src/fvm/checkpoint.rs, fendermint/vm/interpreter/src/fvm/exec.rs
Changes the `end_block` processing so that it doesn't try to fetch the power table from CometBFT, which may not respond to requests yet, for example (maybe) because it's trying to replay the last block it failed on. 
The asynchronous `broadcast_incomplete_signatures` method still gets the power table from CometBFT because that's the only place where the history is preserved, but if that fails, at least it will be retried later.
=> FIX: Do not go to CometBFT during end_block for the power table

fendermint/testing/smoke-test/Makefile.toml, infra/scripts/cometbft.toml
Sets some non-default CometBFT subscription limits, because in our case the `ethapi` container subscribes on behalf of users, and turning Ethereum filters into CometBFT transactions is prone to a combinatorial explosion [here](https://github.com/consensus-shipyard/fendermint/blob/2f02238ec355422f31845031ee39e61fbd903c1a/fendermint/eth/api/src/filters.rs#L93), as demonstrated by [this test](https://github.com/consensus-shipyard/fendermint/blob/2f02238ec355422f31845031ee39e61fbd903c1a/fendermint/eth/api/src/filters.rs#L776). 
Even the [FEVM test suite](https://github.com/consensus-shipyard/fevm-contract-tests/blob/main/test/ethers.js/ERC20.js#L94-L173) subscribes to more than the default limits.
=> CONFIG: Set subscription limits

infra/scripts/fendermint.toml
When you are starting validator through infra scripts - it will put cometbft data files into ~/.ipc/${SUBNET_ID}/${NODE_NAME}/cometbft, but Fendermint data will go into ~/.ipc/${SUBNET_ID}/fendermint for some reason, making it impossible to run multiple validators of the same subnet on 1 machine. This PR is intended to fix this behavior.
=> Fix Fendermint folder

fendermint/eth/api/src/apis/eth.rs, fendermint/testing/smoke-test/scripts/init.sh, fendermint/vm/interpreter/src/fvm/check.rs, fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/query.rs
The initial estimation sets the gas limit to `BLOCK_GAS_LIMIT` which could result in "insufficient funds". This PR changes it to zero for the duration of `estimate_gassed_msg` and then restores it at the end.
=> DEBUG: Gas logging and a tweak to set prices to 0 for initial estimation

fendermint/vm/topdown/src/error.rs, fendermint/vm/topdown/src/sync.rs
Fix look ahead null block error. 
This is a tricky edge case, say the current height is 100 and chain head is 1000 and our block fetching limit is 100. So we will be fetching from height 100 to 200 in this batch. Now, when in the loop we queried till block 199 and we need to fetch the top down messages. Because we need the block hash at block 200, so we query block 200 first  to get the block hash. But sadly block 200 is a null block which throws an error. We should fetch block 201. As a safety precaution, if 201 is a null block ,we need to fetch 202 and so on. Theoretically, we can go all the way to block head. But block head is not considered finalised, so we put a `look_ahead_limit`. 
According to the old logic, the `look_ahead_limit` is just the end block height of the current batch, …
=> Look ahead limit use finalized height

Cargo.lock, Makefile, docker/builder.ci.Dockerfile, docker/builder.local.Dockerfile, docs/demos/milestone-1/fendermint-demo.sh, fendermint/eth/api/src/conv/from_tm.rs
Started getting errors in CI about new fields in ethers: https://github.com/consensus-shipyard/fendermint/actions/runs/6906307060/job/18791062964 
Perhaps the `Cargo.lock` file doesn't apply on the test? That would explain why it takes long to compile even after the application has been built :thinking: 
Actually in [both](https://github.com/consensus-shipyard/fendermint/actions/runs/6906529196/job/18791777648?pr=435) failed CI cases it failed in the docker build, so it might be related to https://github.com/rust-lang/cargo/issues/7169
Okay, the PR will also update the `cargo install` commands to use `--locked` so that it respects the `Cargo.lock` file. Going to test that out in https://github.com/consensus-shipyard/fendermint/pull/435 which doesn't include the `cargo update` I did here.
=> FIX: Update ethers with new fields and use cargo install --locked

Cargo.lock, fendermint/vm/interpreter/src/fvm/state/mod.rs, fendermint/vm/interpreter/src/fvm/state/snapshot.rs, fendermint/vm/snapshot/Cargo.toml, fendermint/vm/snapshot/src/lib.rs, fendermint/vm/snapshot/src/manager.rs
Closes #355 
Closes #358 
This is just a skeleton for a snapshot manager. It listens to notifications about new heights where snapshots should be taken and exports the data to a CAR file. It's not wired in, and doesn't implement all the functions which are covered by upcoming tasks, such as removing old files, listing available snapshots, etc.
=> FM-355: Snapshot manager

Cargo.lock, fendermint/app/Cargo.toml, fendermint/app/src/app.rs, fendermint/app/src/cmd/run.rs
Closes #357 
Changes the `App` to notify the snapshotter about newly committed blocks. The snapshotter is a new optional constructor dependency of the `App` currently unset, so we don't end up exporting data with nothing to clean it up yet.
=> FM-357: Notify the snapshot manager about new commits

fendermint/app/src/app.rs, fendermint/vm/snapshot/src/manager.rs, fendermint/vm/snapshot/src/manifest.rs
Closes #361 
Implements the `load_snapshot_chunk` ABCI method. It looks for the snapshot requested; if it exists it tries to load it from the disk. 
I did not build in any protection against the snapshot not being deleted between the time we find the record in memory and when we try to read it. I don't want to read it inside the STM transaction because that wouldn't guarantee that the pruning task doesn't commit while this one is running, so it's the same from that perspective, but its worse because it can re-read files if the transaction gets retried. 
What would solve it if we updated the snapshot item with a timestamp of when it was last requested and did not delete if it was recent, but I'm not sure if it can't be abused. 
Another option is to just mark it as being read right now, and …
=> FM-361: Serve snapshot chunks

fendermint/app/src/app.rs, fendermint/vm/interpreter/src/fvm/state/snapshot.rs, fendermint/vm/snapshot/src/client.rs, fendermint/vm/snapshot/src/lib.rs, fendermint/vm/snapshot/src/manager.rs, fendermint/vm/snapshot/src/manifest.rs, fendermint/vm/snapshot/src/state.rs
Closes #365 
* When the last chunk is saved we return a `SnapshotItem`
* The `SnapshotItem::import` is used to load the data into a blockstore and validate that the imported metadata matches.
* If successful the `App` state is updated to the manifest. 
Doesn't contain: 
* Tests, deferred to https://github.com/consensus-shipyard/fendermint/issues/363
* The clearing of the `/tmp` directory - we can still investigate the snapshot contents after we're done
* The offering of the imported snapshot for others - we'll offer the next snapshot we make, but not this, although we could if we copied the contents from `/tmp` to the persistent place
* Anything clever like importing the CAR file into a temporary namespace in RocksDB, or trying to _not_ import the artificial metadata field. This is a …
=> FM-365: Commit snapshot

fendermint/vm/interpreter/src/fvm/exec.rs, fendermint/vm/interpreter/src/fvm/mod.rs
Follow up for https://github.com/consensus-shipyard/fendermint/pull/426
I missed this part when making that change: it still tries to connect to CometBFT in `end_block`. This change ignores any error as a synonym for catching up.
=> FIX: Do not fail if status doesn't respond in the interpreter

fendermint/eth/api/src/apis/eth.rs
Equivalent of https://github.com/filecoin-project/lotus/pull/11471
Introduces an `Eip1559TransactionRequestCompat` type next to our `TypedTransactionRequestCompat` which we use to deserialize JSON requests. It accepts `input` or `data`, preferring `input`, before being mapped to the `ethers` type. 
Instead of adding both fields I used the approach in I found [here](https://users.rust-lang.org/t/how-can-i-handle-duplicate-fields-when-specifying-multiple-aliases-using-serde/46426/6). 
I also tried with `#[serde(rename="input", alias = "data")]` but that does not accept duplicate fields.
Eventually ended up with Raul's suggestion of adding `input` but using `flatten` to wrap the original, which requires the minimum amount of code. 
Also opened a PR in `ethers` but ended up only adding an …
=> FIX: Accept 'input' or 'data' or both in transaction request

fendermint/eth/api/examples/ethers.rs, fendermint/eth/api/src/conv/from_tm.rs, fendermint/testing/smoke-test/Makefile.toml, fendermint/vm/message/src/conv/from_eth.rs, fendermint/vm/message/src/conv/from_fvm.rs, fendermint/vm/message/src/signed.rs
Fixes https://github.com/consensus-shipyard/fendermint/issues/351
The `RawBytes` type from `fvm_ipld_encoding` strikes again. Unlike in `to_eth_typed_transaction`, in `to_eth_transaction` I forgot that `Message::params` contains IPLD bytes that have to be decoded to get rid of the length prefix. The result was that the `Transaction::input` field returned from the Ethereum API did not match the `Eip1559TranasctionRequest::data` field the client sent, it was wrapped as an IPLD byte vector. This gets me every time :disappointed:
=> FIX: to_eth_transaction set wrong input bytes

fendermint/app/options/src/eth.rs, fendermint/app/src/cmd/eth.rs, fendermint/eth/api/Cargo.toml, fendermint/eth/api/src/apis/mod.rs, fendermint/eth/api/src/client.rs, fendermint/eth/api/src/lib.rs, fendermint/rpc/src/client.rs, fendermint/testing/smoke-test/Makefile.toml, infra/docker-compose.yml, infra/scripts/ethapi.toml
Fixes #427 
Replaces the use of the `WebSocketClient` in the Ethereum API facade with a new `HybridClient` that wraps it and uses a normal `HttpClient` as well as a `WebSocketClient` under the hood. The former should be more resilient as it doesn't maintain a persistent connection with CometBFT, while the latter is managed by a `HybridClientDriver` that reconnects if it encounters the `"failed to send to internal channel"` error.
With this solution the `ethapi` container should heal itself and doesn't need to be restarted. In the event of the CometBFT connection being dropped, the active WebSocket subscriptions from our own clients should get an error when they try to consume the data, resulting in those connections being closed, forcing them to re-subscribe.
=> FM-427: HybridClient

Makefile
Hopefully this will fix the build for now. Not worth spending too much time discussing this because these out-of-sync problems will vanish with the monorepo.
=> build: lock actors to last pre-refactor commit.
